using Application.Common.CurrentUser;
using Application.Common.DayToDate;
using Application.Common.DayToDate.Iface;
using Application.Common.Geography.Iface;
using Application.Common.Geography.Services;
using Application.Common.Helpers;
using Application.Common.Helpers.Iface;
using Application.Common.Interface;
using Application.Common.SpotPlayer;
using Application.Maping;
using Application.Services.Accounting.DriverSrv;
using Application.Services.Accounting.DriverSrv.Iface;
using Application.Services.Accounting.OtpVerifySrv;
using Application.Services.Accounting.OtpVerifySrv.Iface;
using Application.Services.Accounting.PermissionSrv.Iface;
using Application.Services.Accounting.PetSrv;
using Application.Services.Accounting.PetSrv.Iface;
using Application.Services.Accounting.RolePermission;
using Application.Services.Accounting.RolePermission.Iface;
using Application.Services.Accounting.RoleSrv.Iface;
using Application.Services.Accounting.TicketItemSrv.Iface;
using Application.Services.Accounting.TicketSrv.Iface;
using Application.Services.Accounting.UserPerRecordSrv;
using Application.Services.Accounting.UserPerRecordSrv.Iface;
using Application.Services.Accounting.UserPetPictureSrv;
using Application.Services.Accounting.UserPetPictureSrv.Iface;
using Application.Services.Accounting.UserPetSrv;
using Application.Services.Accounting.UserPetSrv.Iface;
using Application.Services.Accounting.UserProductSrv;
using Application.Services.Accounting.UserProductSrv.Iface;
using Application.Services.Accounting.UserSrv.Iface;
using Application.Services.Accounting.UserTokenSrv.Iface;
using Application.Services.Accounting.UserTokenSrv.Srv;
using Application.Services.BankSrv;
using Application.Services.CategorySrv;
using Application.Services.CategorySrv.Iface;
using Application.Services.CommonSrv.CitySrv;
using Application.Services.CommonSrv.CitySrv.Iface;
using Application.Services.CommonSrv.CommentLikeSrv;
using Application.Services.CommonSrv.CommentLikeSrv.Iface;
using Application.Services.CommonSrv.CountrySrv;
using Application.Services.CommonSrv.CountrySrv.Iface;
using Application.Services.CommonSrv.NeighborhoodSrv;
using Application.Services.CommonSrv.NeighborhoodSrv.Iface;
using Application.Services.CommonSrv.PushBroadcastSrv;
using Application.Services.CommonSrv.PushBroadcastSrv.Iface;
using Application.Services.CommonSrv.PushSubscriptionSrv;
using Application.Services.CommonSrv.PushSubscriptionSrv.Iface;
using Application.Services.CommonSrv.SearchSrv;
using Application.Services.CommonSrv.SearchSrv.Iface;
using Application.Services.CommonSrv.StateSrv;
using Application.Services.CommonSrv.StateSrv.Iface;
using Application.Services.CompanionAssistanceSrvs.CompanionAssistanceAssistanceReportSrv;
using Application.Services.CompanionSrv.CompanionAssistancePackageSrv;
using Application.Services.CompanionSrv.CompanionAssistancePackageSrv.Iface;
using Application.Services.CompanionSrv.CompanionAssistanceSrv;
using Application.Services.CompanionSrv.CompanionAssistanceSrv.Iface;
using Application.Services.CompanionSrv.CompanionAssistanceTimeSrv;
using Application.Services.CompanionSrv.CompanionAssistanceTimeSrv.Iface;
using Application.Services.CompanionSrv.CompanionAssistanceTypeSrv;
using Application.Services.CompanionSrv.CompanionAssistanceTypeSrv.Iface;
using Application.Services.CompanionSrv.CompanionAssistanceUserSrv;
using Application.Services.CompanionSrv.CompanionAssistanceUserSrv.Iface;
using Application.Services.CompanionSrv.CompanionReserveSrv;
using Application.Services.CompanionSrv.CompanionReserveSrv.Iface;
using Application.Services.CompanionSrvs.AssistanceQuestionnaireSrv;
using Application.Services.CompanionSrvs.AssistanceQuestionnaireSrv.Iface;
using Application.Services.CompanionSrvs.AssistanceSrv;
using Application.Services.CompanionSrvs.AssistanceSrv.Iface;
using Application.Services.CompanionSrvs.CompanionAssistancePackagePictureSrv;
using Application.Services.CompanionSrvs.CompanionAssistancePackagePictureSrv.Iface;
using Application.Services.CompanionSrvs.CompanionAssistanceReportSrv.Iface;
using Application.Services.CompanionSrvs.CompanionInsurancePackageSaleSrv;
using Application.Services.CompanionSrvs.CompanionInsurancePackageSaleSrv.Iface;
using Application.Services.CompanionSrvs.CompanionInsurancePackageSrv;
using Application.Services.CompanionSrvs.CompanionInsurancePackageSrv.Iface;
using Application.Services.CompanionSrvs.CompanionPetSrv;
using Application.Services.CompanionSrvs.CompanionPetSrv.Iface;
using Application.Services.CompanionSrvs.CompanionReportSrv;
using Application.Services.CompanionSrvs.CompanionReportSrv.Iface;
using Application.Services.CompanionSrvs.CompanionReserveCommentRateSrv;
using Application.Services.CompanionSrvs.CompanionReserveCommentRateSrv.Iface;
using Application.Services.CompanionSrvs.CompanionReserveCommentSrv;
using Application.Services.CompanionSrvs.CompanionReserveCommentSrv.Iface;
using Application.Services.CompanionSrvs.CompanionReserveExcelSrv;
using Application.Services.CompanionSrvs.CompanionReserveExcelSrv.Iface;
using Application.Services.CompanionSrvs.CompanionReserveUserPetSrv;
using Application.Services.CompanionSrvs.CompanionReserveUserPetSrv.Iface;
using Application.Services.CompanionSrvs.CompanionSrv;
using Application.Services.CompanionSrvs.CompanionSrv.Iface;
using Application.Services.CompanionSrvs.CompanionTypeSrv;
using Application.Services.CompanionSrvs.CompanionTypeSrv.Iface;
using Application.Services.CompanionSrvs.CompanionUserSrv;
using Application.Services.CompanionSrvs.CompanionUserSrv.Iface;
using Application.Services.CompanionSrvs.CompanionZoneSrv;
using Application.Services.CompanionSrvs.CompanionZoneSrv.Iface;
using Application.Services.Content.AddressSrv;
using Application.Services.Content.BannerSrv;
using Application.Services.Content.BannerSrv.Iface;
using Application.Services.Content.CargoSrv;
using Application.Services.Content.CargoSrv.Iface;
using Application.Services.Content.ContactUsGroupSrv;
using Application.Services.Content.ContactUsGroupSrv.Iface;
using Application.Services.Content.ContactUsSrv;
using Application.Services.Content.ContactUsSrv.Iface;
using Application.Services.Content.DeliveryDistanceSrv;
using Application.Services.Content.DeliverySrv;
using Application.Services.Content.DetailSrv;
using Application.Services.Content.DetailSrv.Iface;
using Application.Services.Content.DiscussionAnswerLikeSrv;
using Application.Services.Content.DiscussionAnswerLikeSrv.Iface;
using Application.Services.Content.DiscussionAnswerSrv;
using Application.Services.Content.DiscussionAnswerSrv.Iface;
using Application.Services.Content.DiscussionQuestionSrv;
using Application.Services.Content.DiscussionQuestionSrv.Iface;
using Application.Services.Content.GalleryItemSrv;
using Application.Services.Content.GalleryItemSrv.Iface;
using Application.Services.Content.GallerySrv;
using Application.Services.Content.GallerySrv.Iface;
using Application.Services.Content.HashtagSrv;
using Application.Services.Content.HashtagSrv.Iface;
using Application.Services.Content.NewsletterSrv;
using Application.Services.Content.NewsletterSrv.Iface;
using Application.Services.Content.PostCategorySrv;
using Application.Services.Content.PostCategorySrv.Iface;
using Application.Services.Content.PostCommentSrv.Iface;
using Application.Services.Content.PostFileSrv;
using Application.Services.Content.PostFileSrv.Iface;
using Application.Services.Content.PostHashtagSrv;
using Application.Services.Content.PostHashtagSrv.Iface;
using Application.Services.Content.PostPictureSrv;
using Application.Services.Content.PostPictureSrv.Iface;
using Application.Services.Content.PostProductSrv;
using Application.Services.Content.PostProductSrv.Iface;
using Application.Services.Content.PostSrv;
using Application.Services.Content.PostSrv.Iface;
using Application.Services.Content.StaticPageSrv;
using Application.Services.Content.StaticPageSrv.Iface;
using Application.Services.Content.StoryGroupSrv;
using Application.Services.Content.StoryGroupSrv.Iface;
using Application.Services.Filing.FileSrv;
using Application.Services.Filing.FileSrv.Iface;
using Application.Services.Filing.PictureSrv;
using Application.Services.Filing.PictureSrv.Iface;
using Application.Services.Language.BrandLangSrv;
using Application.Services.Language.BrandLangSrv.Iface;
using Application.Services.Language.CategoryLangSrv;
using Application.Services.Language.CategoryLangSrv.Iface;
using Application.Services.Language.CityLangSrv;
using Application.Services.Language.CityLangSrv.Iface;
using Application.Services.Language.CodeGroupLangSrv;
using Application.Services.Language.CodeGroupLangSrv.Iface;
using Application.Services.Language.CodeLangSrv;
using Application.Services.Language.CodeLangSrv.Iface;
using Application.Services.Language.FeatureItemLangSrv;
using Application.Services.Language.FeatureItemLangSrv.Iface;
using Application.Services.Language.FeatureLangSrv;
using Application.Services.Language.FeatureLangSrv.Iface;
using Application.Services.Language.FullNameFieldLangSrv;
using Application.Services.Language.FullNameFieldLangSrv.Iface;
using Application.Services.Language.GalleryLangSrv;
using Application.Services.Language.GalleryLangSrv.Iface;
using Application.Services.Language.NameFieldLangSrv;
using Application.Services.Language.NameFieldLangSrv.Iface;
using Application.Services.Language.PostLangSrv;
using Application.Services.Language.PostLangSrv.Iface;
using Application.Services.Language.ProductLangSrv;
using Application.Services.Language.ProductLangSrv.Iface;
using Application.Services.Language.SeoFieldLangSrv;
using Application.Services.Language.SeoFieldLangSrv.Iface;
using Application.Services.Language.StateLangSrv;
using Application.Services.Language.StateLangSrv.Iface;
using Application.Services.Language.VarietyLangSrv;
using Application.Services.Language.VarietyLangSrv.Iface;
using Application.Services.MerchantSrv;
using Application.Services.Order.AddressSrv.iface;
using Application.Services.Order.BankSrv.Iface;
using Application.Services.Order.CartSrv;
using Application.Services.Order.CartSrv.Iface;
using Application.Services.Order.DeliveryDistanceSrv.iface;
using Application.Services.Order.DeliverySrv.iface;
using Application.Services.Order.MerchantSrv.Iface;
using Application.Services.Order.PaymentSrv;
using Application.Services.Order.PaymentSrv.Iface;
using Application.Services.Order.ProductOrderItemItemSrv;
using Application.Services.Order.ProductOrderItemSrv.Iface;
using Application.Services.Order.ProductOrderSrv;
using Application.Services.Order.ProductOrderSrv.Iface;
using Application.Services.Order.ProductOrderStoreItemSrv;
using Application.Services.Order.ProductOrderStoreSrv.Iface;
using Application.Services.Order.RebateSrv;
using Application.Services.Order.RebateSrv.Iface;
using Application.Services.PansionSrvs.PansionCommentSrv;
using Application.Services.PansionSrvs.PansionCommentSrv.Iface;
using Application.Services.PansionSrvs.PansionPetSrv;
using Application.Services.PansionSrvs.PansionPetSrv.Iface;
using Application.Services.PansionSrvs.PansionPictureSrv;
using Application.Services.PansionSrvs.PansionPictureSrv.Iface;
using Application.Services.PansionSrvs.PansionReserveSrv;
using Application.Services.PansionSrvs.PansionReserveSrv.Iface;
using Application.Services.PansionSrvs.PansionSrv;
using Application.Services.PansionSrvs.PansionSrv.Iface;
using Application.Services.PermissionSrv;
using Application.Services.ProductSrv.ProductCategorySrv;
using Application.Services.ProductSrvs.BrandCategorySrv;
using Application.Services.ProductSrvs.BrandCategorySrv.Iface;
using Application.Services.ProductSrvs.BrandSrv;
using Application.Services.ProductSrvs.BrandSrv.Iface;
using Application.Services.ProductSrvs.DiscountGroupSrv;
using Application.Services.ProductSrvs.DiscountGroupSrv.Iface;
using Application.Services.ProductSrvs.DiscountSrv;
using Application.Services.ProductSrvs.DiscountSrv.IFace;
using Application.Services.ProductSrvs.FeatureItemSrv;
using Application.Services.ProductSrvs.FeatureSrv;
using Application.Services.ProductSrvs.FeatureSrv.Iface;
using Application.Services.ProductSrvs.ProductCategorySrv.Iface;
using Application.Services.ProductSrvs.ProductCommentSrv;
using Application.Services.ProductSrvs.ProductCommentSrv.Iface;
using Application.Services.ProductSrvs.ProductExelSrv;
using Application.Services.ProductSrvs.ProductExelSrv.iface;
using Application.Services.ProductSrvs.ProductFeatureValueSrv;
using Application.Services.ProductSrvs.ProductFeatureValueSrv.Iface;
using Application.Services.ProductSrvs.ProductFileSrv;
using Application.Services.ProductSrvs.ProductFileSrv.Iface;
using Application.Services.ProductSrvs.ProductItemSrv;
using Application.Services.ProductSrvs.ProductItemSrv.Iface;
using Application.Services.ProductSrvs.ProductLikeSrv;
using Application.Services.ProductSrvs.ProductLikeSrv.Iface;
using Application.Services.ProductSrvs.ProductPictureSrv;
using Application.Services.ProductSrvs.ProductPictureSrv.Iface;
using Application.Services.ProductSrvs.ProductRelateSrv;
using Application.Services.ProductSrvs.ProductRelateSrv.Iface;
using Application.Services.ProductSrvs.ProductReportSrv;
using Application.Services.ProductSrvs.ProductReportSrv.Iface;
using Application.Services.ProductSrvs.ProductSrv;
using Application.Services.ProductSrvs.ProductSrv.Iface;
using Application.Services.ProductSrvs.StoreCommentSrv;
using Application.Services.ProductSrvs.StoreCommentSrv.Iface;
using Application.Services.ProductSrvs.StoreSrv;
using Application.Services.ProductSrvs.VarietyItemSrv;
using Application.Services.ProductSrvs.VarietyItemSrv.Iface;
using Application.Services.ProductSrvs.VarietySrv;
using Application.Services.ProductSrvs.VarietySrv.Iface;
using Application.Services.ProductSrvs.WalletSrv;
using Application.Services.ProductSrvs.WalletSrv.IFace;
using Application.Services.ReminderSrvs.ReminderCycleSrv;
using Application.Services.ReminderSrvs.ReminderCycleSrv.Iface;
using Application.Services.ReminderSrvs.ReminderSrv;
using Application.Services.ReminderSrvs.ReminderSrv.Iface;
using Application.Services.ReminderSrvs.ReminderTypeSrv;
using Application.Services.ReminderSrvs.ReminderTypeSrv.Iface;
using Application.Services.RoleSrv;
using Application.Services.Setting.BaseDetailSrv;
using Application.Services.Setting.BaseDetailSrv.Iface;
using Application.Services.Setting.CodeGroupSrv;
using Application.Services.Setting.CodeGroupSrv.Iface;
using Application.Services.Setting.CodeSrv;
using Application.Services.Setting.CodeSrv.Iface;
using Application.Services.Setting.EmailSrv;
using Application.Services.Setting.EmailSrv.Iface;
using Application.Services.Setting.MapKeyService;
using Application.Services.Setting.MapKeyService.Iface;
using Application.Services.Setting.MessageSenderSrv;
using Application.Services.Setting.MessageSenderSrv.Iface;
using Application.Services.Setting.NoticeSrv;
using Application.Services.Setting.NoticeSrv.Iface;
using Application.Services.Setting.NotifyMessageSrv;
using Application.Services.Setting.NotifyMessageSrv.Iface;
using Application.Services.Setting.SettingSrv;
using Application.Services.Setting.SmsSrv;
using Application.Services.Setting.SmsSrv.Iface;
using Application.Services.StoreSrv.Iface;
using Application.Services.StoreSrv.StoreUserSrv;
using Application.Services.StoreSrvs.StoreUserSrv.Iface;
using Application.Services.TicketItemSrv;
using Application.Services.TicketSrv;
using Application.Services.TripSrv.PriceCalculationSrv;
using Application.Services.TripSrv.PriceCalculationSrv.Iface;
using Application.Services.TripSrv.TripAddressSrv;
using Application.Services.TripSrv.TripAddressSrv.Iface;
using Application.Services.TripSrv.TripOptionSrv;
using Application.Services.TripSrv.TripOptionSrv.Iface;
using Application.Services.TripSrv.TripSrv;
using Application.Services.TripSrv.TripSrv.Iface;
using Application.Services.TripSrv.TripStopSrv;
using Application.Services.TripSrv.TripStopSrv.Iface;
using Application.Services.UserSrv;
using Application.Services.WeekDaySrv.WeekDaySrv;
using Application.Services.WeekDaySrv.WeekDaySrv.Iface;
using AutoMapper;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc.Razor;
using Microsoft.Extensions.DependencyInjection;
using System.Collections.Generic;
using System.Globalization;
using System.Threading.Tasks;


namespace Application.Configures;

public static class ConfigureServices
{
    public static IServiceCollection AddApplicationServices(this IServiceCollection services)
    {
        services.AddLocalization(options => options.ResourcesPath = "Resource");

        services.Configure<RequestLocalizationOptions>(options =>
        {
            var supportedCultures = new List<CultureInfo>
                    {
                        new CultureInfo("fa"),
                        //new CultureInfo("en-US"),
                        //new CultureInfo("ar"),
                        //new CultureInfo("tr")
                    };
            options.DefaultRequestCulture = new RequestCulture("fa", "fa");
            options.SupportedCultures = supportedCultures;
            options.SupportedUICultures = supportedCultures;
            options.ApplyCurrentCultureToResponseHeaders = true;
            options.RequestCultureProviders.Insert(0, new CustomRequestCultureProvider(async context =>
            {
                //var userLangs = context.Request.Headers["Accept-Language"].ToString().ToLower();
                //if (userLangs == "en-us,en;q=0.9")
                //    userLangs = "";
                //else if (userLangs == "en")
                //{
                //    userLangs = "en-us";
                //}
                //var firstLang = userLangs.Split(',').FirstOrDefault();
                //var defaultLang = string.IsNullOrEmpty(firstLang) ? "fa" : firstLang;

                return await Task.FromResult(new ProviderCultureResult("fa", "fa"));
            }));
        });
        services.AddControllers().AddViewLocalization(LanguageViewLocationExpanderFormat.Suffix)
                        .AddDataAnnotationsLocalization();
        services.AddHttpContextAccessor();
        services.AddHttpClient();
        services.AddScoped<ICurrentUserHelper, CurrentUserHelper>();
        services.AddScoped<IRoleService, RoleService>();
        services.AddScoped<IUserService, UserService>();
        services.AddScoped<IPermissionService, PermissionService>();
        services.AddScoped<IUserTokenService, UserTokenService>();
        services.AddScoped<IOnTokenValidatedService, OnTokenValidatedService>();
        services.AddScoped<IOnTokenNotValidService, OnTokenNotValidService>();
        services.AddScoped<IOnTokenChallenge, OnTokenChallenge>();
        services.AddScoped<ICodeGroupService, CodeGroupService>();
        services.AddScoped<ICodeService, CodeService>();
        services.AddScoped<IBrandService, BrandService>();
        services.AddScoped<ICityService, CityService>();
        services.AddScoped<IStateService, StateService>();
        services.AddScoped<ICategoryService, CategoryService>();
        services.AddScoped<IPictureService, PictureService>();
        services.AddScoped<IFileService, FileService>();
        services.AddScoped<IPostService, PostService>();
        services.AddScoped<IProductService, ProductService>();
        services.AddScoped<IRolePermissionService, RolePermissionService>();
        services.AddScoped<IBrandCategoryService, BrandCategoryService>();
        services.AddScoped<IPostFileService, PostFileService>();
        services.AddScoped<IPostPictureService, PostPictureService>();
        services.AddScoped<IProductPictureService, ProductPictureService>();
        services.AddScoped<IProductFileService, ProductFileService>();
        services.AddScoped<IPostLangService, PostLangService>();
        services.AddScoped<ICategoryLangService, CategoryLangService>();
        services.AddScoped<IBrandLangService, BrandLangService>();
        services.AddScoped<IProductLangService, ProductLangService>();
        services.AddScoped<ICodeLangService, CodeLangService>();
        services.AddScoped<ICodeGroupLangService, CodeGroupLangService>();
        services.AddScoped<IFeatureLangService, FeatureLangService>();
        services.AddScoped<IVarietyService, VarietyService>();
        services.AddScoped<IVarietyItemService, VarietyItemService>();
        services.AddScoped<IVarietyLangService, VarietyLangService>();
        services.AddScoped<IFeatureItemLangService, FeatureItemLangService>();
        services.AddScoped<ISeoFieldLangService, SeoFieldLangService>();
        services.AddScoped<INameFieldLangService, NameFieldLangService>();
        services.AddScoped<IGalleryService, GalleryService>();
        services.AddScoped<IGalleryItemService, GalleryItemService>();
        services.AddScoped<ICityLangService, CityLangService>();
        services.AddScoped<IStateLangService, StateLangService>();
        services.AddScoped<IGalleryLangService, GalleryLangService>();
        services.AddScoped<IFullNameFieldLangService, FullNameFieldLangService>();
        services.AddScoped<IPostCommentService, PostCommentService>();
        services.AddScoped<IProductCommentService, ProductCommentService>();
        services.AddScoped<IHashtagService, HashtagService>();
        services.AddScoped<IPostHashtagService, PostHashtagService>();
        services.AddScoped<IPostCategoryService, PostCategoryService>();
        services.AddScoped<IOtpVerifyService, OtpVerifyService>();
        services.AddScoped<IBannerService, BannerService>();
        services.AddScoped<IStaticPageService, StaticPageService>();
        services.AddScoped<IDetailService, DetailService>();
        services.AddScoped<IContactUsService, ContactUsService>();
        services.AddScoped<ISmsService, SmsService>();
        services.AddScoped<IEmailService, EmailService>();
        services.AddScoped<IMessageSenderService, MessageSenderService>();
        services.AddScoped<IProductCategoryService, ProductCategoryService>();
        services.AddScoped<IRegixHelper, RegixHelper>();
        services.AddScoped<IAddressService, AddressService>();
        services.AddScoped<ICartService, CartService>();
        services.AddScoped<IBankService, BankService>();
        services.AddScoped<IMerchantService, MerchantService>();
        services.AddScoped<IRebateService, RebateService>();
        services.AddScoped<IProductOrderService, ProductOrderService>();
        services.AddScoped<IProductOrderItemService, ProductOrderItemService>();
        services.AddScoped<IPaymentService, PaymentService>();
        services.AddScoped<IProductLikeService, ProductLikeService>();
        services.AddScoped<ITicketService, TicketService>();
        services.AddScoped<ITicketItemService, TicketItemService>();
        services.AddScoped<ISpotPlayer, SpotPlayerHelper>();
        services.AddScoped<INewsletterService, NewsletterService>();
        services.AddScoped<IContactUsGroupService, ContactUsGroupService>();
        services.AddScoped<IPostProductService, PostProductService>();
        services.AddScoped<IProductRelateService, ProductRelateService>();
        services.AddScoped<IFeatureService, FeatureService>();
        services.AddScoped<IFeatureItemService, FeatureItemService>();
        services.AddScoped<IProductFeatureValueService, ProductFeatureValueService>();
        services.AddScoped<ICategoryFeatureService, CategoryFeatureService>();
        services.AddScoped<IDeliveryDistanceService, DeliveryDistanceService>();
        services.AddScoped<IDeliveryService, DeliveryService>();
        services.AddScoped<IBaseDetailService, BaseDetailService>();
        services.AddScoped<IAdminSettingService, AdminSettingService>();
        services.AddScoped<IAdminSettingHelper, AdminSettingHelper>();
        services.AddScoped<IProductOrderStoreService, ProductOrderStoreService>();
        services.AddScoped<IProductItemService, ProductItemService>();
        services.AddScoped<IStoreService, StoreService>();
        services.AddScoped<IStoreCommentService, StoreCommentService>();
        services.AddScoped<ICategoryFeatureService, CategoryFeatureService>();
        services.AddScoped<IStoreUserService, StoreUserService>();
        services.AddScoped<IDiscountService, DiscountService>();
        services.AddScoped<IDiscountGroupService, DiscountGroupService>();
        services.AddScoped<ISearchService, SearchService>();
        services.AddScoped<IProductExcelService, ProductExcelService>();
        services.AddScoped<IWalletService, WalletService>();
        services.AddScoped<IPetService, PetService>();
        services.AddScoped<IUserPetService, UserPetService>();
        services.AddScoped<IUserProductService, UserProductService>();
        services.AddScoped<ITripService, TripService>();
        services.AddScoped<IPriceCalculationService, PriceCalculationService>();
        services.AddScoped<IMapKeyService, MapKeyService>();
        services.AddScoped<IGeographyService, MapIrService>();
        services.AddScoped<IAssistanceService, AssistanceService>();
        services.AddScoped<ICompanionService, CompanionService>();
        services.AddScoped<ICompanionAssistanceService, CompanionAssistanceService>();
        services.AddScoped<ICompanionAssistancePackageService, CompanionAssistancePackageService>();
        services.AddScoped<ICompanionAssistanceTimeService, CompanionAssistanceTimeService>();
        services.AddScoped<ICompanionAssistanceUserService, CompanionAssistanceUserService>();
        services.AddScoped<ICompanionReserveService, CompanionReserveService>();
        services.AddScoped<IWeekDayService, WeekDayService>();
        services.AddScoped<INeighborhoodService, NeighborhoodService>();
        services.AddScoped<ICompanionAssistanceTypeService, CompanionAssistanceTypeService>();
        services.AddScoped<ICompanionReserveCommentService, CompanionReserveCommentService>();
        services.AddScoped<ICompanionReserveCommentRateService, CompanionReserveCommentRateService>();
        services.AddScoped<IAssistanceQuestionnaireService, AssistanceQuestionnaireService>();
        services.AddScoped<IDriverService, DriverService>();
        services.AddScoped<ICompanionUserService, CompanionUserService>();
        services.AddScoped<IProductReportService, ProductReportService>();
        services.AddScoped<ICompanionReportService, CompanionReportService>();
        services.AddScoped<ICompanionAssistanceReportService, CompanionAssistanceReportService>();
        services.AddScoped<ICommentLikeService, CommentLikeService>();
        services.AddScoped<IDiscussionQuestionService, DiscussionQuestionService>();
        services.AddScoped<IDiscussionAnswerService, DiscussionAnswerService>();
        services.AddScoped<IDiscussionAnswerLikeService, DiscussionAnswerLikeService>();
        services.AddScoped<INoticeService, NoticeService>();
        services.AddScoped<ICountryService, CountryService>();
        services.AddScoped<ITripOptionService, TripOptionService>();
        services.AddScoped<ITripStopService, TripStopService>();
        services.AddScoped<ITripAddressService, TripAddressService>();
        services.AddScoped<ICargoService, CargoService>();
        services.AddScoped<ICompanionInsurancePackageService, CompanionInsurancePackageService>();
        services.AddScoped<ICompanionInsurancePackageSaleService, CompanionInsurancePackageSaleService>();
        services.AddScoped<IReminderTypeService, ReminderTypeService>();
        services.AddScoped<IReminderCycleService, ReminderCycleService>();
        services.AddScoped<IReminderService, ReminderService>();
        services.AddScoped<ICompanionPetService, CompanionPetService>();
        services.AddScoped<ICompanionTypeService, CompanionTypeService>();
        services.AddScoped<IUserPetRecordService, UserPetRecordService>();
        services.AddScoped<IDayToDateService, DayToDateService>();
        services.AddScoped<ICompanionReserveExcelService, CompanionReserveExcelService>();
        services.AddScoped<INotifyMessageService, NotifyMessageService>();
        services.AddScoped<ICompanionReserveUserPetService, CompanionReserveUserPetService>();
        services.AddScoped<ICompanionAssistancePackagePictureService, CompanionAssistancePackagePictureService>();
        services.AddScoped<IPansionService, PansionService>();
        services.AddScoped<IPansionPetService, PansionPetService>();
        services.AddScoped<IPansionCommentService, PansionReserveCommentService>();
        services.AddScoped<IPansionPictureService, PansionPictureService>();
        services.AddScoped<IPansionReserveService, PansionReserveService>();
        services.AddScoped<ICompanionZoneService, CompanionZoneService>();
        services.AddScoped<IUserPetPictureService, UserPetPictureService>();
        services.AddScoped<IPushSubscriptionService, PushSubscriptionService>();
        services.AddScoped<IPushBroadcastService, PushBroadcastService>();
        services.AddScoped<IStoryGroupService, StoryGroupService>();


        services.AddCors(option => option.AddPolicy("AllowAnyOrigin", b => b.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod()));
        // تنظیم MapperConfiguration
        var mapperConfig = new MapperConfiguration(cfg =>
        {
            cfg.AddProfile(new AllMap());
        });

        // ایجاد Mapper از تنظیمات
        IMapper mapper = mapperConfig.CreateMapper();

        // افزودن Mapper به DI Container
        services.AddSingleton(mapper);
        return services;
    }
}
