//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Description.
        /// </summary>
        public static string AdminDescription {
            get {
                return ResourceManager.GetString("AdminDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After Rent.
        /// </summary>
        public static string AfterRent {
            get {
                return ResourceManager.GetString("AfterRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssistanceName.
        /// </summary>
        public static string AssistanceName {
            get {
                return ResourceManager.GetString("AssistanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Price.
        /// </summary>
        public static string BasePrice {
            get {
                return ResourceManager.GetString("BasePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Code.
        /// </summary>
        public static string BonusCode {
            get {
                return ResourceManager.GetString("BonusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booker Name.
        /// </summary>
        public static string BookerName {
            get {
                return ResourceManager.GetString("BookerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Id.
        /// </summary>
        public static string BrandId {
            get {
                return ResourceManager.GetString("BrandId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Name.
        /// </summary>
        public static string BrandName {
            get {
                return ResourceManager.GetString("BrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Id.
        /// </summary>
        public static string CategoryId {
            get {
                return ResourceManager.GetString("CategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeValue.
        /// </summary>
        public static string CodeValue {
            get {
                return ResourceManager.GetString("CodeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companion Name.
        /// </summary>
        public static string CompanionName {
            get {
                return ResourceManager.GetString("CompanionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companion Reserves.
        /// </summary>
        public static string CompanionReserves {
            get {
                return ResourceManager.GetString("CompanionReserves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companion Share.
        /// </summary>
        public static string CompanionShare {
            get {
                return ResourceManager.GetString("CompanionShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toman.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount End Date.
        /// </summary>
        public static string DiscountEndDate {
            get {
                return ResourceManager.GetString("DiscountEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Percent.
        /// </summary>
        public static string DiscountPercent {
            get {
                return ResourceManager.GetString("DiscountPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureColor.
        /// </summary>
        public static string FeatureColor {
            get {
                return ResourceManager.GetString("FeatureColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureCount.
        /// </summary>
        public static string FeatureCount {
            get {
                return ResourceManager.GetString("FeatureCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureCountry.
        /// </summary>
        public static string FeatureCountry {
            get {
                return ResourceManager.GetString("FeatureCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureCustomize.
        /// </summary>
        public static string FeatureCustomize {
            get {
                return ResourceManager.GetString("FeatureCustomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureSize.
        /// </summary>
        public static string FeatureSize {
            get {
                return ResourceManager.GetString("FeatureSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureTook.
        /// </summary>
        public static string FeatureTook {
            get {
                return ResourceManager.GetString("FeatureTook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureUsage.
        /// </summary>
        public static string FeatureUsage {
            get {
                return ResourceManager.GetString("FeatureUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Weight.
        /// </summary>
        public static string FeatureWeight {
            get {
                return ResourceManager.GetString("FeatureWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immediate delivery.
        /// </summary>
        public static string ImmediateDelivery {
            get {
                return ResourceManager.GetString("ImmediateDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Id.
        /// </summary>
        public static string ItemId {
            get {
                return ResourceManager.GetString("ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online payment.
        /// </summary>
        public static string OnlinePayment {
            get {
                return ResourceManager.GetString("OnlinePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Detail.
        /// </summary>
        public static string OperatorDetail {
            get {
                return ResourceManager.GetString("OperatorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Final Price.
        /// </summary>
        public static string OperatorFinalPrice {
            get {
                return ResourceManager.GetString("OperatorFinalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Name.
        /// </summary>
        public static string OperatorName {
            get {
                return ResourceManager.GetString("OperatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Stuff Price.
        /// </summary>
        public static string OperatorStuffPrice {
            get {
                return ResourceManager.GetString("OperatorStuffPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Wages Price.
        /// </summary>
        public static string OperatorWagesPrice {
            get {
                return ResourceManager.GetString("OperatorWagesPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Price.
        /// </summary>
        public static string PackagePrice {
            get {
                return ResourceManager.GetString("PackagePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Price.
        /// </summary>
        public static string PaymentPrice {
            get {
                return ResourceManager.GetString("PaymentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet Type.
        /// </summary>
        public static string PetType {
            get {
                return ResourceManager.GetString("PetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PictureId.
        /// </summary>
        public static string PictureId {
            get {
                return ResourceManager.GetString("PictureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre Payment Price.
        /// </summary>
        public static string PrePaymentPrice {
            get {
                return ResourceManager.GetString("PrePaymentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Id.
        /// </summary>
        public static string ProductId {
            get {
                return ResourceManager.GetString("ProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Label.
        /// </summary>
        public static string ProductLabel {
            get {
                return ResourceManager.GetString("ProductLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Item List.
        /// </summary>
        public static string ProductsItemList {
            get {
                return ResourceManager.GetString("ProductsItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products List.
        /// </summary>
        public static string ProductsList {
            get {
                return ResourceManager.GetString("ProductsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Avg.
        /// </summary>
        public static string RateAvg {
            get {
                return ResourceManager.GetString("RateAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Count.
        /// </summary>
        public static string RateCount {
            get {
                return ResourceManager.GetString("RateCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebate Price.
        /// </summary>
        public static string RebatePrice {
            get {
                return ResourceManager.GetString("RebatePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve Id.
        /// </summary>
        public static string ReserveId {
            get {
                return ResourceManager.GetString("ReserveId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Name.
        /// </summary>
        public static string SecondName {
            get {
                return ResourceManager.GetString("SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Count.
        /// </summary>
        public static string SellCount {
            get {
                return ResourceManager.GetString("SellCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Limit Count.
        /// </summary>
        public static string SellLimitCount {
            get {
                return ResourceManager.GetString("SellLimitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharePercent.
        /// </summary>
        public static string SharePercent {
            get {
                return ResourceManager.GetString("SharePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Share.
        /// </summary>
        public static string SiteShare {
            get {
                return ResourceManager.GetString("SiteShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusId.
        /// </summary>
        public static string StatusId {
            get {
                return ResourceManager.GetString("StatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Name.
        /// </summary>
        public static string StatusName {
            get {
                return ResourceManager.GetString("StatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoreId.
        /// </summary>
        public static string StoreId {
            get {
                return ResourceManager.GetString("StoreId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Name.
        /// </summary>
        public static string StoreName {
            get {
                return ResourceManager.GetString("StoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeId.
        /// </summary>
        public static string TypeId {
            get {
                return ResourceManager.GetString("TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Name.
        /// </summary>
        public static string TypeName {
            get {
                return ResourceManager.GetString("TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string UpdateDate {
            get {
                return ResourceManager.GetString("UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variety.
        /// </summary>
        public static string Variety {
            get {
                return ResourceManager.GetString("Variety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variety2Id.
        /// </summary>
        public static string Variety2Id {
            get {
                return ResourceManager.GetString("Variety2Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variety2 Name.
        /// </summary>
        public static string Variety2Name {
            get {
                return ResourceManager.GetString("Variety2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variety Id.
        /// </summary>
        public static string VarietyId {
            get {
                return ResourceManager.GetString("VarietyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variety Name.
        /// </summary>
        public static string VarietyName {
            get {
                return ResourceManager.GetString("VarietyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Count.
        /// </summary>
        public static string VisitCount {
            get {
                return ResourceManager.GetString("VisitCount", resourceCulture);
            }
        }
    }
}
