//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Notification {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notification() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Notification", typeof(Notification).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccessDenied.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Choose.
        /// </summary>
        public static string AlreadyChoose {
            get {
                return ResourceManager.GetString("AlreadyChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Is Companion.
        /// </summary>
        public static string AlreadyIsCompanion {
            get {
                return ResourceManager.GetString("AlreadyIsCompanion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already is driver.
        /// </summary>
        public static string AlreadyIsDriver {
            get {
                return ResourceManager.GetString("AlreadyIsDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is not correct.
        /// </summary>
        public static string AmountNotCorrect {
            get {
                return ResourceManager.GetString("AmountNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus amount added to wallet successfully.
        /// </summary>
        public static string BonusAmountAddedToWalletSuccessfully {
            get {
                return ResourceManager.GetString("BonusAmountAddedToWalletSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus code can not be yours.
        /// </summary>
        public static string BonusCodeCanNotBeYours {
            get {
                return ResourceManager.GetString("BonusCodeCanNotBeYours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus has already been added to the wallet for this ProductOrder.
        /// </summary>
        public static string BonusHasAlreadyBeenAddedToTheWalletForThisProductOrder {
            get {
                return ResourceManager.GetString("BonusHasAlreadyBeenAddedToTheWalletForThisProductOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart is Empty.
        /// </summary>
        public static string CartIsEmpty {
            get {
                return ResourceManager.GetString("CartIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Value.
        /// </summary>
        public static string CodeValue {
            get {
                return ResourceManager.GetString("CodeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate value.
        /// </summary>
        public static string DuplicateValue {
            get {
                return ResourceManager.GetString("DuplicateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on start payment.
        /// </summary>
        public static string ErrorOnStartPayment {
            get {
                return ResourceManager.GetString("ErrorOnStartPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Allow.
        /// </summary>
        public static string FileNotAllow {
            get {
                return ResourceManager.GetString("FileNotAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Price Is Not Available.
        /// </summary>
        public static string FinalPriceIsNotAvailable {
            get {
                return ResourceManager.GetString("FinalPriceIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Account Now Is Available.
        /// </summary>
        public static string GoldAccountNowIsAvailable {
            get {
                return ResourceManager.GetString("GoldAccountNowIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have Been Reserved.
        /// </summary>
        public static string HaveBeenReserved {
            get {
                return ResourceManager.GetString("HaveBeenReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient funds.
        /// </summary>
        public static string InsufficientFunds {
            get {
                return ResourceManager.GetString("InsufficientFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient inventory.
        /// </summary>
        public static string InsufficientInventory {
            get {
                return ResourceManager.GetString("InsufficientInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid bonus code.
        /// </summary>
        public static string InvalidBonusCode {
            get {
                return ResourceManager.GetString("InvalidBonusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code.
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data.
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid time format.
        /// </summary>
        public static string InvalidTimeFormat {
            get {
                return ResourceManager.GetString("InvalidTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token is invalid.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to buy.
        /// </summary>
        public static string ItIsNotPossibleToBuy {
            get {
                return ResourceManager.GetString("ItIsNotPossibleToBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Plate Number.
        /// </summary>
        public static string LicensePlateNumber {
            get {
                return ResourceManager.GetString("LicensePlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number changed successfully.
        /// </summary>
        public static string MobileChangedSuccessfully {
            get {
                return ResourceManager.GetString("MobileChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found.
        /// </summary>
        public static string NothingFound {
            get {
                return ResourceManager.GetString("NothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to use this rebate code.
        /// </summary>
        public static string NotPossibleUseRebateCode {
            get {
                return ResourceManager.GetString("NotPossibleUseRebateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed.
        /// </summary>
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please answer the questions.
        /// </summary>
        public static string PleaseAnswerTheQuestions {
            get {
                return ResourceManager.GetString("PleaseAnswerTheQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Change The Status.
        /// </summary>
        public static string PleaseChangeTheStatus {
            get {
                return ResourceManager.GetString("PleaseChangeTheStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why You Are Cancelling.
        /// </summary>
        public static string PleaseEnterCancelDetail {
            get {
                return ResourceManager.GetString("PleaseEnterCancelDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter either mobile or email.
        /// </summary>
        public static string PleaseEnterEitherMobileOrEmail {
            get {
                return ResourceManager.GetString("PleaseEnterEitherMobileOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter File.
        /// </summary>
        public static string PleaseEnterFile {
            get {
                return ResourceManager.GetString("PleaseEnterFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter From Date.
        /// </summary>
        public static string PleaseEnterFromDate {
            get {
                return ResourceManager.GetString("PleaseEnterFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter The Activation Value Reason.
        /// </summary>
        public static string PleaseEnterTheActivationValueReason {
            get {
                return ResourceManager.GetString("PleaseEnterTheActivationValueReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter The Address.
        /// </summary>
        public static string PleaseEnterTheAddress {
            get {
                return ResourceManager.GetString("PleaseEnterTheAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter The Admin Detail.
        /// </summary>
        public static string PleaseEnterTheAdminDetail {
            get {
                return ResourceManager.GetString("PleaseEnterTheAdminDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the amount.
        /// </summary>
        public static string PleaseEnterTheAmount {
            get {
                return ResourceManager.GetString("PleaseEnterTheAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the code.
        /// </summary>
        public static string PleaseEnterTheCode {
            get {
                return ResourceManager.GetString("PleaseEnterTheCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter The Driver.
        /// </summary>
        public static string PleaseEnterTheDriver {
            get {
                return ResourceManager.GetString("PleaseEnterTheDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter The License Plate Number.
        /// </summary>
        public static string PleaseEnterTheLicensePlateNumber {
            get {
                return ResourceManager.GetString("PleaseEnterTheLicensePlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PleaseEnterTheName.
        /// </summary>
        public static string PleaseEnterTheName {
            get {
                return ResourceManager.GetString("PleaseEnterTheName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the password.
        /// </summary>
        public static string PleaseEnterThePassword {
            get {
                return ResourceManager.GetString("PleaseEnterThePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the phone.
        /// </summary>
        public static string PleaseEnterThePhone {
            get {
                return ResourceManager.GetString("PleaseEnterThePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the token.
        /// </summary>
        public static string PleaseEnterTheToken {
            get {
                return ResourceManager.GetString("PleaseEnterTheToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter The Vehicle.
        /// </summary>
        public static string PleaseEnterTheVehicle {
            get {
                return ResourceManager.GetString("PleaseEnterTheVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Time Range.
        /// </summary>
        public static string PleaseEnterTimeRange {
            get {
                return ResourceManager.GetString("PleaseEnterTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the address.
        /// </summary>
        public static string PleaseSelectTheAddress {
            get {
                return ResourceManager.GetString("PleaseSelectTheAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the delivery type.
        /// </summary>
        public static string PleaseSelectTheDeliveryType {
            get {
                return ResourceManager.GetString("PleaseSelectTheDeliveryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the merchant.
        /// </summary>
        public static string PleaseSelectTheMerchant {
            get {
                return ResourceManager.GetString("PleaseSelectTheMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set destination.
        /// </summary>
        public static string PleaseSetDestination {
            get {
                return ResourceManager.GetString("PleaseSetDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set origin.
        /// </summary>
        public static string PleaseSetOrigin {
            get {
                return ResourceManager.GetString("PleaseSetOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Set User Pet.
        /// </summary>
        public static string PleaseSetUserPet {
            get {
                return ResourceManager.GetString("PleaseSetUserPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the first variation value..
        /// </summary>
        public static string PleaseSpecifyFirstVariationValue {
            get {
                return ResourceManager.GetString("PleaseSpecifyFirstVariationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve has Not Completed Yet.
        /// </summary>
        public static string ReservehasNotCompletedYet {
            get {
                return ResourceManager.GetString("ReservehasNotCompletedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not find.
        /// </summary>
        public static string ResourceNotFind {
            get {
                return ResourceManager.GetString("ResourceNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one type.
        /// </summary>
        public static string SelectAtLeastOneType {
            get {
                return ResourceManager.GetString("SelectAtLeastOneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings are not complete.
        /// </summary>
        public static string SettingsAreNotComplete {
            get {
                return ResourceManager.GetString("SettingsAreNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date Must Be From Tommarow.
        /// </summary>
        public static string StartDateMustBeFromTommarow {
            get {
                return ResourceManager.GetString("StartDateMustBeFromTommarow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added to cart.
        /// </summary>
        public static string SuccessfullyAddedToCart {
            get {
                return ResourceManager.GetString("SuccessfullyAddedToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully completed and previous variations were removed..
        /// </summary>
        public static string SuccessfullyCompletedPreviousVariationsWereRemoved {
            get {
                return ResourceManager.GetString("SuccessfullyCompletedPreviousVariationsWereRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bonus code is wrong.
        /// </summary>
        public static string TheBonusCodeIsWrong {
            get {
                return ResourceManager.GetString("TheBonusCodeIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The calculation of shares has already been done..
        /// </summary>
        public static string TheCalculationOfSharesHasAlreadyBeenDone {
            get {
                return ResourceManager.GetString("TheCalculationOfSharesHasAlreadyBeenDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code is duplicate.
        /// </summary>
        public static string TheCodeIsDuplicate {
            get {
                return ResourceManager.GetString("TheCodeIsDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code is wrong.
        /// </summary>
        public static string TheCodeIsWrong {
            get {
                return ResourceManager.GetString("TheCodeIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date is not correct.
        /// </summary>
        public static string TheDateNotCorrect {
            get {
                return ResourceManager.GetString("TheDateNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is duplicate.
        /// </summary>
        public static string TheEmailAddressIsDuplicate {
            get {
                return ResourceManager.GetString("TheEmailAddressIsDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is wrong.
        /// </summary>
        public static string TheEmailAddressIsWrong {
            get {
                return ResourceManager.GetString("TheEmailAddressIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email of Email address change request has been sent.
        /// </summary>
        public static string TheEmailChangeRequestSent {
            get {
                return ResourceManager.GetString("TheEmailChangeRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered number is not correct.
        /// </summary>
        public static string TheEnteredNumberNotCorrect {
            get {
                return ResourceManager.GetString("TheEnteredNumberNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The final amount has not yet been recorded for this reservation..
        /// </summary>
        public static string TheFinalPriceHasNotYetBeenRecordedForThisReserve {
            get {
                return ResourceManager.GetString("TheFinalPriceHasNotYetBeenRecordedForThisReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The label is duplicate.
        /// </summary>
        public static string TheLabelIsDuplicate {
            get {
                return ResourceManager.GetString("TheLabelIsDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit of the number of uses of this discount code has been reached.
        /// </summary>
        public static string TheLimitUsesDiscountCodeReached {
            get {
                return ResourceManager.GetString("TheLimitUsesDiscountCodeReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sms of the Mobile change request has been sent.
        /// </summary>
        public static string TheMobileChangeRequestSent {
            get {
                return ResourceManager.GetString("TheMobileChangeRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mobile number is duplicate.
        /// </summary>
        public static string TheMobileNumberIsDuplicate {
            get {
                return ResourceManager.GetString("TheMobileNumberIsDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mobile number is wrong.
        /// </summary>
        public static string TheMobileNumberIsWrong {
            get {
                return ResourceManager.GetString("TheMobileNumberIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TheNameIsDuplicate.
        /// </summary>
        public static string TheNameIsDuplicate {
            get {
                return ResourceManager.GetString("TheNameIsDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number is more than stock.
        /// </summary>
        public static string TheNumberIsMoreThanStock {
            get {
                return ResourceManager.GetString("TheNumberIsMoreThanStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of wrongs is greater than the limit.
        /// </summary>
        public static string TheNumberOfWrongsIsGreaterThanThelimit {
            get {
                return ResourceManager.GetString("TheNumberOfWrongsIsGreaterThanThelimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is wrong.
        /// </summary>
        public static string ThePasswordIsWrong {
            get {
                return ResourceManager.GetString("ThePasswordIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The percentage range is not correct.
        /// </summary>
        public static string ThePercentageRangeNotCorrect {
            get {
                return ResourceManager.GetString("ThePercentageRangeNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product is unavailable.
        /// </summary>
        public static string TheProductUnavailable {
            get {
                return ResourceManager.GetString("TheProductUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The range entered is not correct.
        /// </summary>
        public static string TheRangeEnteredIsNotCorrect {
            get {
                return ResourceManager.GetString("TheRangeEnteredIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recovery code was emailed.
        /// </summary>
        public static string TheRecoveryCodeWasEmailed {
            get {
                return ResourceManager.GetString("TheRecoveryCodeWasEmailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recovery code was sent by SMS.
        /// </summary>
        public static string TheRecoveryCodeWasSentBySMS {
            get {
                return ResourceManager.GetString("TheRecoveryCodeWasSentBySMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time range must be between 0 and 23..
        /// </summary>
        public static string TheTimeRangeMustBeBetween0And23 {
            get {
                return ResourceManager.GetString("TheTimeRangeMustBeBetween0And23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time to use this code has not arrived.
        /// </summary>
        public static string TheTimeUseCodeNotArrived {
            get {
                return ResourceManager.GetString("TheTimeUseCodeNotArrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user account is blocked.
        /// </summary>
        public static string TheUserAccountIsBlocked {
            get {
                return ResourceManager.GetString("TheUserAccountIsBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This article has already been edited.
        /// </summary>
        public static string ThisArticleHasAlreadyBeenEdited {
            get {
                return ResourceManager.GetString("ThisArticleHasAlreadyBeenEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This discount code has expired.
        /// </summary>
        public static string ThisDiscountCodeExpired {
            get {
                return ResourceManager.GetString("ThisDiscountCodeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Insurance Is Not For This Pet.
        /// </summary>
        public static string ThisInsuranceIsNotForThisPet {
            get {
                return ResourceManager.GetString("ThisInsuranceIsNotForThisPet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThisReserveIsCompleted.
        /// </summary>
        public static string ThisReserveIsCompleted {
            get {
                return ResourceManager.GetString("ThisReserveIsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Reserve Is Not Blong To You.
        /// </summary>
        public static string ThisReserveIsNotBlongToYou {
            get {
                return ResourceManager.GetString("ThisReserveIsNotBlongToYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThisReserveIsPaid.
        /// </summary>
        public static string ThisReserveIsPaid {
            get {
                return ResourceManager.GetString("ThisReserveIsPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Reserve State Has Completed Before.
        /// </summary>
        public static string ThisReserveStateHasCompletedBefore {
            get {
                return ResourceManager.GetString("ThisReserveStateHasCompletedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Trip Has Been Reserved For Another Driver.
        /// </summary>
        public static string ThisTripHasBeenReservedForAnotherDriver {
            get {
                return ResourceManager.GetString("ThisTripHasBeenReservedForAnotherDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times have overlap.
        /// </summary>
        public static string TimesHaveOverlap {
            get {
                return ResourceManager.GetString("TimesHaveOverlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token expired.
        /// </summary>
        public static string TokenExpired {
            get {
                return ResourceManager.GetString("TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To time must be bigger than from time.
        /// </summary>
        public static string ToTimeMustBeBiggerThanFromTime {
            get {
                return ResourceManager.GetString("ToTimeMustBeBiggerThanFromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip has Not Completed Yet.
        /// </summary>
        public static string TriphasNotCompletedYet {
            get {
                return ResourceManager.GetString("TriphasNotCompletedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessfully.
        /// </summary>
        public static string Unsuccess {
            get {
                return ResourceManager.GetString("Unsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFount {
            get {
                return ResourceManager.GetString("UserNotFount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with the provided BonusCode not found.
        /// </summary>
        public static string UserWithTheProvidedBonusCodeNotFound {
            get {
                return ResourceManager.GetString("UserWithTheProvidedBonusCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varieties should be different.
        /// </summary>
        public static string VarietiesShouldBeDifferent {
            get {
                return ResourceManager.GetString("VarietiesShouldBeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Already Have Online Trip.
        /// </summary>
        public static string YouAlreadyHaveOnlineTrip {
            get {
                return ResourceManager.GetString("YouAlreadyHaveOnlineTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can Not Cancel This Reservation.
        /// </summary>
        public static string YouCanNotCancelThisReservation {
            get {
                return ResourceManager.GetString("YouCanNotCancelThisReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Have Already Purchased This Course.
        /// </summary>
        public static string YouHaveAlreadyPurchasedThisCourse {
            get {
                return ResourceManager.GetString("YouHaveAlreadyPurchasedThisCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already purchased this product.
        /// </summary>
        public static string YouHaveAlreadyPurchasedThisProduct {
            get {
                return ResourceManager.GetString("YouHaveAlreadyPurchasedThisProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not permission.
        /// </summary>
        public static string YouHaveNotPermission {
            get {
                return ResourceManager.GetString("YouHaveNotPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to add information for this Companion..
        /// </summary>
        public static string YouHaveNotPermissionToAddInformationForThisCompanion {
            get {
                return ResourceManager.GetString("YouHaveNotPermissionToAddInformationForThisCompanion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Cargo Request Is Not Accepted.
        /// </summary>
        public static string YourCargoRequestIsNotAccepted {
            get {
                return ResourceManager.GetString("YourCargoRequestIsNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Report Has Been Submited For This Companion Assistance Before.
        /// </summary>
        public static string YourReportHasBeenSubmitedForThisCompanionAssistanceBefore {
            get {
                return ResourceManager.GetString("YourReportHasBeenSubmitedForThisCompanionAssistanceBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Report Has Been Submited For This Companion Before.
        /// </summary>
        public static string YourReportHasBeenSubmitedForThisCompanionBefore {
            get {
                return ResourceManager.GetString("YourReportHasBeenSubmitedForThisCompanionBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Report Has Been Submited For This Product Before.
        /// </summary>
        public static string YourReportHasBeenSubmitedForThisProductBefore {
            get {
                return ResourceManager.GetString("YourReportHasBeenSubmitedForThisProductBefore", resourceCulture);
            }
        }
    }
}
